---
title: "data_access"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(pins)
delta_sites_edi <- pins::pin('https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=6a82451e84be1fe82c9821f30ffc2d7d')
delta_sites <- readr::read_csv(delta_sites_edi, show_col_types = FALSE)
head(delta_sites)
```

## resolving data with content ID
```{r}
library(contentid)

delta_catch_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=015e494911cf35c90089ced5a3127334'
delta_taxa_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=0532048e856d4bd07deea11583b893dd'
delta_effort_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=ace1ef25f940866865d24109b7250955'
delta_sites_edi <- 'https://portal.edirepository.org/nis/dataviewer?packageid=edi.233.2&entityid=6a82451e84be1fe82c9821f30ffc2d7d'

delta_catch_id <- store(delta_catch_edi)
delta_catch_id # recording can be useful if error occurs from update in the future
retrieve(delta_catch_id) # gives the path
delta_cathc <- readr::read_csv(retrieve(delta_catch_id), show_col_types = FALSE)

delta_catch_file <- resolve(delta_catch_id, store = TRUE)
delta_cathc <- readr::read_csv(delta_catch_file, show_col_types = FALSE)
```

