---
title: "Data Cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(dplyr)
library(tidyr)
```

## Data Sources

Read in the data from [KMB](https://knb.ecoinformatics.org/#view/df35b.304.2)

```{r}
catch_original <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")

glimpse(catch_original)
```

## Clean and Reshape data

* remove unnecessary columns

```{r}
catch_data <- catch_original %>% 
  select(-All, -notesRegCode)

glimpse(catch_data)
```

* check column types

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = as.numeric(Chinook))
```

```{r}
i <- which(is.na(catch_clean$Chinook))
i

catch_original[i,]
```

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", "1", Chinook)) %>% 
  mutate(Chinook = as.integer(Chinook))
           
```

* reshape data

```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch")
```

```{r}
catch_long <- catch_long %>% 
  rename(catch_thousands = catch) %>% 
  mutate(catch = catch_thousands *1000)

head(catch_long)
```

* group and summarize data

```{r}
mean_region <- catch_long %>% 
  group_by(Region) %>% 
  summarise(catch_mean = mean(catch), num_obs = n())

head(mean_region)
```

```{r}
cv_yr <- catch_long %>% 
  group_by(Year) %>% 
  summarise(catch_cv = sd(catch)/mean(catch))

head(cv_yr)
```

## Join to regions definitions

```{r}
region_defs <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1") %>% 
    select(code, mgmtArea)

head(region_defs)
```

```{r}
catch_joined <- left_join(catch_long, region_defs, by = c("Region" = "code"))

head(catch_joined)
```

